version: "3"
networks:
  booksroutesnet:
    ipam:
      driver: default
      config:
        - subnet: 192.26.0.1/16
services:
  app:
    image: gutesterregistry.azurecr.io/booksroutes-app:latest
    container_name: app
    networks:
      - booksroutesnet
    ports:
      - "80:80"
      - "8080:8080"
  api:
    image: gutesterregistry.azurecr.io/booksroutes-api:latest
    container_name: api
    networks:
      - booksroutesnet
    ports:
      - "1337:1337"
